### PR TITLE
webview: Do not use Array.from in WebView

### LINKED ISSUE #2905: Uncaught TypeeError: Array.from is not a function
`Uncaught TypeeError: Array.from is not a function` exception is sometimes thrown inside WebView.

### PR DESCRIPTION
**Pull request by borisyankov**
Fixes #2905

`Array.from` is not available on all platform's WebViews we support.
One way to do this is to include a polyfill like this one:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill

Instead we'll use a simlper and sufficient approach - using `Array`'s `slice`
method called on the imageTags array-like object.

### CODE REVIEW

File: src/webview/js/js.js [hunk 1]
```diff
@@ -220,7 +220,8 @@ const scrollToPreserve = (msgId: number, prevBoundTop: number) => {
 
 const appendAuthToImages = auth => {
   const imageTags = document.getElementsByTagName('img');
-  Array.from(imageTags).forEach(img => {
+  const imageTagsArray = Array.prototype.slice.call(imageTags);
```
Comment (gnprice) [inline src/webview/js/js.js]: This is a neat trick!

I feel like it calls for some explanation, or at least some isolation as a thing with a name; it's a bit puzzling at first look. ("Why isn't this reduced to just `imageTags.slice()`?)

Perhaps a function named `arrayFrom`? Perhaps also with a link to this handy section on the MDN page, about exactly this trick:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice#Array-like_objects

**Comment by borisyankov** [comment]
Just a ping that this PR was updated.

File: src/webview/js/js.js [hunk 2]
```diff
@@ -7,6 +7,10 @@ import type {
   MessageInputTyping,
 } from '../webViewHandleUpdates';
 
+// Converts an array-like object to an actual array
+// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice#Array-like_objects
+const arrayFrom = arrayLike => Array.prototype.slice.call(arrayLike);
```
Comment (jackrzhang) [inline src/webview/js/js.js]: The comment could mention that Array.from won't necessarily be supported in the WebView, which is why this function exists in the first place.

It's not too much extra effort to look at the commit body, but I think that's the other important detail here, and it would be more visible in the comment.

**Comment by gnprice** [comment]
Thanks @borisyankov , and @jackrzhang for the comment -- merged!

I agree with Jack's remark, and added a commit on top to do that.
