### PR TITLE
Fix last `connectFlowFixMe`; and delete it!

### LINKED ISSUE #3451: Fix type errors hidden by `connect`
Historically the `connect` of `react-redux` has had a `flow-typed` libdef that largely defeats type-checking on it -- so e.g. a component can have a prop with a type that doesn't actually match the selector that supplies it, or a `mapStateToProps` callback can assume that its `props` argument has some property that is never actually specified.

With #3450 we get a version of `connect` that makes type-checking work. It turns out there are a number of errors out there that this was hiding! In addition to the many such errors that I fixed a week or two ago (accounting for most of the commits in cae19530f^..f89f317ff), there are 13 more files with these errors, now marked with `commitFlowFixMe`.

A workflow to fix them:
1. Change all uses of `connectFlowFixMe` to plain `connect`: `perl -i -0pe 's/connectFlowFixMe/connect/g' src/*/*.js`
2. Run `yarn flow` to see errors.
3. Pick a file with errors; fix the errors.
4. Commit just that file.
5. Repeat from step 2.

Then send a PR with any one or more commits made this way.

### PR DESCRIPTION
**Pull request by gnprice**
Fixes #3451, as the final cleanup after most call sites were resolved in #3789.

The commit message on the most interesting step is:

---

status bar [nfc]: Fix connectFlowFixMe.

The thing that had made it gnarly to use our well-typed `connect` here was that we both took `backgroundColor` in as a prop of the outer component and then returned a `backgroundColor` from the `mapStateToProps` callback, to override the former as a prop on the inner component.

The same fact is also a source of complexity and surprise when trying to read the code as a human, because we're giving the same name to two slightly different things right next to each other.  Doubly so because those two things are a prop of a component passed to `connect` and the same-named prop of the resulting component -- and it's routine across the rest of our codebase that when a prop exists on both, it's passed straight through verbatim.

So, disentangle that by introducing a distinct name.  And then lift the fixme!

This whole "title background color" logic is still rather tanglier than I'd like: in how `narrow` and a forced `backgroundColor` are implicitly mutually exclusive as props to `ZulipStatusBar`; in the use of DEFAULT_TITLE_BACKGROUND_COLOR aka `'transparent'` both as a value with its own substantive meaning and as a sentinel meaning "no stream here"; in how this component and `ChatNavBar` share this bit of UI logic, but under the covers via a putative selector.  It'd be good to disentangle those.  But now at least we have types here.

### CODE REVIEW

File: src/subscriptions/subscriptionSelectors.js [hunk 1]
```diff
@@ -27,6 +27,11 @@ export const getSubscriptionsById: Selector<Map<number, Subscription>> = createS
     new Map(subscriptions.map(subscription => [subscription.stream_id, subscription])),
 );
 
+export const getSubscriptionsByName: Selector<Map<string, Subscription>> = createSelector(
```
Comment (chrisbobbe) [inline src/subscriptions/subscriptionSelectors.js]: Is `name` (the stream name) a unique identifier for `Subscription`s? In subscriptionsReducer, it looks like `stream_id` is considered unique:

```
    case EVENT_SUBSCRIPTION:
      switch (action.op) {
        case 'add':
          return state.concat(
            action.subscriptions.filter(x => !state.find(y => x.stream_id === y.stream_id)),
          );
```

Perhaps they're both unique? The existence of the [`get_stream_id` endpoint](https://zulipchat.com/api/get-stream-id) suggests so. Maybe it would be useful to have code comments on certain API types about any unique identifiers they have.

**Comment by chrisbobbe** [comment]
This looks mostly good to me; I just posted a comment with a question, above.

This is a partial rewrite of https://github.com/zulip/zulip-mobile/pull/3912, right, but there are still some nice fixes that I think Ray has in mind on that one.

File: src/subscriptions/subscriptionSelectors.js (hunk 1 above)
Comment (gnprice) [reply src/subscriptions/subscriptionSelectors.js]: Yeah, they are. It'd be better to use the numeric ID, but that's a long-open ongoing migration. I just filed #3918 to describe it.

The one real disadvantage of stream names vs. IDs -- other than the disadvantages of having *two* different ways, which complicates the code -- is that names can change.

The reason this codepath is doing its lookup by name is ultimately that it has a `Narrow`, and our `Narrow` type uses emails for users (cf #3764) and names for streams. We should fix that, but it'll be rather a project in itself.

**Comment by gnprice** [comment]
Thanks @chrisbobbe for the review! Merged.


> This is a partial rewrite of #3912, right, but there are still some nice fixes that I think Ray has in mind on that one.

Yeah, there's a commit which sweeps through to use `??` where applicable, which would be good to have. After your comment above, Ray closed #3912 and suggested he might continue that as its own small PR, which makes sense. (There's a tweak or two to be made from the version in #3912.)
