### PR TITLE
Fix mute icon in sidebar and streams screen

### LINKED ISSUE #376: Muted streams not marked as muted in left sidebar
Noticing this on master. Muted streams are shown with a '#' instead of a mute icon

### PR DESCRIPTION
**Pull request by borisyankov**
Fixes #376 

Also, fixes an icon sizing bug.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@borisyankov, it looks like you've already signed the Dropbox CLA. Thanks!

File: src/streamlist/StreamList.js [hunk 1]
```diff
@@ -34,6 +33,7 @@ export default class StreamList extends React.Component {
             description={showDescriptions && x.description}
             color={x.color}
             isSelected={x.name === selected}
+            isMuted={typeof x.in_home_view !== 'undefined' && !x.in_home_view}
```
Comment (neerajwahi) [inline src/streamlist/StreamList.js]: Why the `typeof x.in_home_view !== 'undefined`?

Comment (borisyankov) [inline src/streamlist/StreamList.js]: For some views we don't have that information, and !undefined is true, but we want to not show the mute icon if no data available.

Comment (neerajwahi) [inline src/streamlist/StreamList.js]: Ah ok. How about `x.in_home_view === false`?

Also, mind leaving a comment about how it can be undefined which means that we shouldn't show the mute icon?

Comment (borisyankov) [inline src/streamlist/StreamList.js]: Duh, of course this is better :)
I'll change it and add a comment.

**Comment by borisyankov** [comment]
Updated.
