### PR TITLE
android: Request WRITE_EXTERNAL_STORAGE permission.

### LINKED ISSUE #3115: android: Fix use of `WRITE_EXTERNAL_STORAGE` permission.
This is part of https://github.com/zulip/zulip-mobile/issues/3075.

This error from React-Native comes up on the debug build when I try to download an image on an emulator running API 28:

 

On an installation from Play Store, the app crashes.

See [this document](https://developer.android.com/training/permissions/requesting).

(@zulipbot add "area: android" "crash")
(@zulipbot claim)

### PR DESCRIPTION
**Pull request by jackrzhang**
The first time a user attempts to download an image, permission to write to external storage (the SD card) should be requested. If permission is granted by the user, the image should proceed to download.

If permission is denied, the image will not be fetched, and the corresponding text 'Storage permission denied' is shown. Any subsequent time that a user attempts to download an image, a 'rationale' modal will appear with explaining why the app needs permissions, and the permission will once again be requested.

<p align="center">
android-request-permissions-write-external-storage-1
</p>

If a user instructs that the permission not be asked for again, then subsequent attempts to download an image will only result in showing the text 'Storage permission denied', though the permission can always be changed via Android Settings.

<p align="center">
android-request-permissions-write-external-storage-2
</p>

For reference, see [React Native 0.57's PermissionsAndroid API](https://facebook.github.io/react-native/docs/permissionsandroid) and [Android's developer documentation on requesting permissions](https://developer.android.com/training/permissions/requesting).

This fixes #3115 and progresses #3075.
@gnprice

### CODE REVIEW

File: src/lightbox/LightboxActionSheet.js [hunk 1]
```diff
@@ -50,7 +50,7 @@ const shareImageDirectly = ({ src, auth }: DownloadImageType) => {
 };
 
 const actionSheetButtons: ButtonType[] = [
-  { title: 'Download file', onPress: downloadImage },
+  { title: 'Download image', onPress: tryToDownloadImage },
```
Comment (borisyankov) [inline src/lightbox/LightboxActionSheet.js]: Make sure to update the `messages_en.json` file.

Comment (jackrzhang) [reply src/lightbox/LightboxActionSheet.js]: Will update!

I wonder if there's any way that this caught via the test suite.

**Comment by jackrzhang** [comment]
(Also, this moves forward #2618.)

**Comment by gnprice** [comment]
Thanks @jackrzhang ! Merged.

I made a few edits on top that I think make the code easier to understand -- please take a look.

I missed @borisyankov 's comment above (sorry!) until I'd already merged:
> Make sure to update the messages_en.json file.

 But actually I think the situation is that these messages -- all the labels in the lightbox action sheet -- are already untranslated even when our volunteer translators have kindly provided translations. :disappointed: Note the lack of any code to act on these strings to find their translations. I also quickly verified just now with German.

So that would be good to fix. Also while we're at it make the new messages in this new flow get translated too. :-)

**Comment by gnprice** [comment]
(#2812 is some background for that translation issue.)
