### PR TITLE
Use result of post request for sending message 

### LINKED ISSUE #1077: Messages are sent multiple times.
Something is going wrong while sending messages. (may be with outbox). Sometimes it is sending multiple times and still indicator is showing.
screen shot 2017-08-22 at 4 49 15 am

https://chat.zulip.org/#narrow/stream/test.20here/topic/v1.2E0.2E18.20.E2.9D.A4.EF.B8.8F

screen shot 2017-08-22 at 4 54 17 am

### PR DESCRIPTION
**Pull request by kunall17**
Fixes #1077 #1074

### CODE REVIEW

File: src/outbox/outboxActions.js [hunk 1]
```diff
@@ -7,6 +7,7 @@ import {
   START_OUTBOX_SENDING,
   FINISHED_OUTBOX_SENDING,
   DELETE_OUTBOX_MESSAGE,
+  MESSAGE_SEND_SUCCESSFUL,
```
Comment (borisyankov) [inline src/outbox/outboxActions.js]: `MESSAGE_SEND_SUCCESS`

File: src/actionConstants.js [hunk 2]
```diff
@@ -75,6 +75,7 @@ export const CANCEL_EDIT_MESSAGE = 'CANCEL_EDIT_MESSAGE';
 export const INIT_ALERT_WORDS = 'INIT_ALERT_WORDS';
 
 export const MESSAGE_SEND = 'MESSAGE_SEND';
```
Comment (borisyankov) [inline src/actionConstants.js]: Would that name be `MESSAGE_SEND_START` ?

File: src/outbox/outboxActions.js [hunk 3]
```diff
@@ -27,40 +28,54 @@ export const deleteOutboxMessage = (localMessageId: number) => ({
...
-        item.type,
-        isPrivateOrGroupNarrow(item.narrow) ? item.narrow[0].operand : item.display_recipient,
-        item.subject,
-        item.content,
-        item.timestamp,
-        state.app.eventQueueId,
-      ),
-    );
+    state.outbox.forEach(async item => {
+      try {
```
Comment (borisyankov) [inline src/outbox/outboxActions.js]: Why this change?

File: src/outbox/outboxActions.js [hunk 4]
```diff
@@ -27,40 +28,54 @@ export const deleteOutboxMessage = (localMessageId: number) => ({
...
+        await sendMessageApi(
```
Comment (borisyankov) [inline src/outbox/outboxActions.js]: Why added await again? This makes the sending sequential.

File: src/outbox/outboxActions.js (hunk 3 above)
Comment (kunall17) [inline src/outbox/outboxActions.js]: Now i'm using the result of POST request, if it is successful then remove the outbox as in the wait period for the EVENT_NEW_MESSAGE with the localMessageId sometimes the outbox triggers again and duplicate messages are sent

File: src/outbox/outboxActions.js (hunk 4 above)
Comment (kunall17) [inline src/outbox/outboxActions.js]: Yup, I want that message sending should be completed before calling finish outbox sending.

File: src/chat/Chat.js [hunk 5]
```diff
@@ -33,7 +33,7 @@ export default class Chat extends PureComponent {
 
   handleSend = () => {
     if (this.listComponent && this.listComponent.scrollToEnd !== undefined) {
-      this.listComponent.scrollToEnd();
+      setTimeout(this.listComponent.scrollToEnd, 300);
```
Comment (kunall17) [inline src/chat/Chat.js]: This change is because when handleSend is triggered (for scrolling), the renderedMessages in MessageListContainer is not updated yet, hence it was not scrolling to the correct position.

File: src/outbox/outboxActions.js (hunk 4 above)
Comment (borisyankov) [inline src/outbox/outboxActions.js]: But you are waiting on each message before sending the next. You can still send them, wait on them with `await Promise.all([`

**Comment by borisyankov** [comment]
Looks good (good enough :) )

File: src/outbox/outboxActions.js (hunk 4 above)
Comment (kunall17) [inline src/outbox/outboxActions.js]: Ohh yeah, will do this another PR as this one is merged!

Comment (borisyankov) [inline src/outbox/outboxActions.js]: I merged this, because I realized your error handling was kinda connected to that.
I would still encourage you to do another PR, but consider how you will handle retries of failed messages too.
