### PR TITLE
Fix crash on submitting blank server URL

### LINKED ISSUE #2095: App Crashing when pressing Enter without any organisation url
Whenever I press Enter without Entering any organisation url the app is crashing,
It needs to say something like no URL in toast

### PR DESCRIPTION
**Pull request by codebu5ter**
Added a checkURLInputIsEmptyOrNot helper method that checks if the server URL is empty and fires an alert asking the user to enter a server URL.

Fixes #2095

### CODE REVIEW

File: src/common/SmartUrlInput.js [hunk 1]
```diff
@@ -22,7 +22,7 @@ type Props = {
   shortAppend: string,
   style?: StyleObj,
   onChange: (value: string) => void,
-  onSubmitEditing: () => Promise<void>,
+  onSubmitEditing: () => void,
```
Comment (jainkuniya) [inline src/common/SmartUrlInput.js]: Why this?

File: src/start/RealmScreen.js [hunk 2]
```diff
@@ -34,6 +34,16 @@ class RealmScreen extends PureComponent<Props, State> {
     error: undefined,
   };
 
+  checkURLInputIsEmptyOrNot = () => {
+    const { realm } = this.state;
+
+    if (realm === '') {
```
Comment (jainkuniya) [inline src/start/RealmScreen.js]: Move this logic to `tryRealm`

File: src/common/SmartUrlInput.js (hunk 1 above)
Comment (codebu5ter) [reply src/common/SmartUrlInput.js]: I did this because the tests were failing, since the onSubmitEditing prop expected an async function (tryRealm), which returned a Promise.

File: src/start/RealmScreen.js (hunk 2 above)
Comment (codebu5ter) [reply src/start/RealmScreen.js]: Understood.

**Comment by codebu5ter** [comment]
@jainkuniya I tested out Slack and found that it disables the submit button, and also disables the submit button on the keyboard for iOS when the input field is empty.
I've implemented the same functionality in my latest commit. Please have a look.

**Comment by borisyankov** [comment]
@codebu5ter I had my doubts about disabling the key but if Slack does it, I am convinced. Good job in providing an example of how another app does it - that strengthens your case.

Please do include only the button disabling code. If it works you don't need to do the `if (realm)` check at all!

**Comment by codebu5ter** [comment]
@borisyankov I included the `if (realm)` check to prevent the crash in case the user presses the return key on the keyboard without typing anything. iOS has a `enablesReturnKeyAutomatically`, which I've also implemented and it disables the return key on an iOS keyboard, but for Android, the realm check is necessary.

Slack also implements it the same way, wherein the return key on the iOS keyboard is disabled, whereas the return key on Android is enabled, but does nothing when pressed, which is the intended functionality here too.

**Comment by codebu5ter** [comment]
@borisyankov Removed the realm check, as requested.

**Comment by borisyankov** [comment]
Looks good now! Thanks for your work!
