### PR TITLE
Add missing emojis. Fix emoji autocomplete

### LINKED ISSUE #260: Some emojis are missing compared to main app
Warning example:
```
Warning: Failed prop type: Invalid prop `name` of value `double_exclamation_mark` supplied to `Icon`, expected one of ["100","1234","interrobang","tm","information_source","left_right_arrow","arrow_up_down","arrow_upper_left","arrow_upper_right","arrow_lower_right","arrow_lower_left","keyboard","sunny","cloud","umbrella","showman","comet","ballot_box_with_check","coffee","shamrock","skull_and_crossbones",
```

@timabbott can we auto generate a file in this format (slight difference of how emoji codes are presented):
https://github.com/zulip/zulip-mobile/blob/master/src/emoji/emojiMap.js

### LINKED ISSUE #284: Exception when clicking back button from AccountDetails screen
To reproduce: click on a user avatar in a message to show the account details screen. Then click on the back button in the navigation bar.

Exception:
```
Warning: Failed prop type: Invalid prop `backgroundColor` supplied to `View`: #NaN
Valid color formats are
  - '#f0f' (#rgb)
  - '#f0fc' (#rgba)
  - '#ff00ff' (#rrggbb)
  - '#ff00ff00' (#rrggbbaa)
  - 'rgb(255, 255, 255)'
  - 'rgba(255, 255, 255, 1.0)'
  - 'hsl(360, 100%, 100%)'
  - 'hsla(360, 100%, 100%, 1.0)'
  - 'transparent'
  - 'red'
  - 0xff00ff00 (0xrrggbbaa)

Bad object: {
  "justifyContent": "center",
  "alignItems": "center",
  "height": 100,
  "width": 100,
  "borderRadius": 12.5,
  "backgroundColor": "#NaN"
}
    in View
    in Unknown (created by Avatar)
    in Avatar (created by AccountDetails)
    in RCTView (created by View)
    in View (created by AccountDetails)
    in RCTView (created by View)
    in View (created by AccountDetails)
...
```

### PR DESCRIPTION
**Pull request by borisyankov**
Fixes #260 
Fixes #284

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@borisyankov, it looks like you've already signed the Dropbox CLA. Thanks!

File: src/account-info/AccountDetailsScreen.js [hunk 1]
```diff
@@ -16,17 +16,21 @@ class AccountDetailsScreen extends Component {
...
 
+  componentWillMount() {
+    this.email = this.props.email;
+  }
+
   render() {
-    const { auth, email, users, fetchMessages, popRoute } = this.props;
-    const { fullName, avatarUrl, status } = users.find(x => x.email === email) || { fullName: 'A', avatarUrl: '', status: 'unknown' };
+    const { auth, users, fetchMessages, popRoute } = this.props;
+    const { fullName, avatarUrl, status } = users.find(x => x.email === this.email) || { fullName: 'A', avatarUrl: '', status: 'unknown' };
```
Comment (neerajwahi) [inline src/account-info/AccountDetailsScreen.js]: We should treat a missing user here as an error instead of showing 'A' with status 'unknown'

File: src/account-info/AccountDetailsScreen.js [hunk 2]
```diff
@@ -16,17 +16,21 @@ class AccountDetailsScreen extends Component {
     avatarUrl: string,
   }
 
+  componentWillMount() {
+    this.email = this.props.email;
```
Comment (neerajwahi) [inline src/account-info/AccountDetailsScreen.js]: Why move `email` to a member variable (instead of directly using `this.props.email` as before)?

Comment (borisyankov) [inline src/account-info/AccountDetailsScreen.js]: It is stored in 'current route' property and the current route changes at the point of animation. Thus during the sliding of the view it is undefined, and this is where the error came from.

File: src/account-info/AccountDetailsScreen.js (hunk 1 above)
Comment (borisyankov) [inline src/account-info/AccountDetailsScreen.js]: It should not even happen now. I just don't want the app to crash if it does.

File: src/account-info/AccountDetailsScreen.js (hunk 2 above)
Comment (neerajwahi) [inline src/account-info/AccountDetailsScreen.js]: Cool can we add that as a comment here? Would be useful to someone reading the code in the future

I don't really like this pattern -- we should revisit later and see if there's a way to avoid having to store state in this component
