### PR TITLE
 compose: Fix image fileName from uri for HEIC image files.

### LINKED ISSUE #2178: Convert HEIC/HEIF images on upload from iOS
(Summary by @gnprice:)

Images created by recent versions of iOS are often in the HEIF format (extension `.heic`), which is a patent-restricted Apple format. When those images are uploaded, they tend to be unreadable elsewhere.

When uploading an image on iOS that's in HEIF format, we should use platform facilities to get or create a JPEG version and upload that.

(Original report follows.)

---

Hi,

I setup zulip today on a Ubuntu 16.04.4 LTS following the installation guide, so far everything looks promising. I found one issue so far or it looks like one at least.

Some pictures on my Iphone are JPG everything works, but some pictures are in HEIC format and here the latest IOS client only show a link like IMG_7113.HEIC no image, if i click the link a web view opens up loading but shows only a white page.

I see the request in the nginx logfile with a 200 status code.

xxxxxxx - - [30/Mar/2018:22:12:11 +0000] "GET /user_uploads/2/92/wPKjGi9juRThwf-r-0bW_HsO/IMG_7113.HEIC HTTP/1.1" 200 65247 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1"

I thought maybe for the web view it would help to add the mime types but that did not change anything.

/etc/nginx/zulip-include/uploads.types
    image/heic                            heic;
    image/heif                            heif;

Thx

Markus

### PR DESCRIPTION
**Pull request by jackrzhang**
Copying the jsdoc comment I've written for `fixFileNameFromUri`:

```js
/**
 * In 2017, Apple adopted a new standard image format, HEIF, which stands
 * for High Efficiency File Format; Apple photos are named with the '.heic'
 * extension. When an image file with the extension '.heic' is uploaded to the
 * server,the image becomes unviewable within a message list. Interestingly,
 * the `file` command line utility reports that images saved under this format
 * are JPEG files, so there's likely some pecularity with how the server handles
 * file uploads based on the extension.
 *
 * If an image file name has the '.heic' extension, and the uri of the image on a
 * mobile device has an extension for the JPEG format, fixFileNameFromUri replaces
 * that extension with '.jpeg'.
 */
```

This resolves #2178.
@gnprice

### CODE REVIEW

File: src/compose/ComposeMenu.js [hunk 1]
```diff
@@ -19,6 +19,26 @@ type Props = {
...
+ * server,the image becomes unviewable within a message list. Interestingly,
+ * the `file` command line utility reports that images saved under this format
+ * are JPEG files, so there's likely some pecularity with how the server handles
+ * file uploads based on the extension.
+ *
+ * If an image file name has the '.heic' extension, and the uri of the image on a
+ * mobile device has an extension for the JPEG format, fixFileNameFromUri replaces
+ * that extension with '.jpeg'.
+ */
+export const fixFileNameFromUri = (uri: string, fileName: string): string => {
```
Comment (borisyankov) [inline src/compose/ComposeMenu.js]: The name of the function can be made better. 'Fix' is a bit generic. 'FileName' might not be exact (we are talking about extension only). Would also adding 'image' somewhere in the name help? (I know I am a bit vague, but trying not to suggest you a concrete name :) )

I would also move this to some of the `/utils/*.js` files.

File: src/compose/ComposeMenu.js [hunk 2]
```diff
@@ -19,6 +19,26 @@ type Props = {
...
+  if (/\.jpe?g$/i.test(uri)) {
```
Comment (borisyankov) [inline src/compose/ComposeMenu.js]: Should we do an `if` for `Platform.OS === 'ios'`?
This might never be `true` on Android, but this `if` will make the behavior more exact to our intentions.

File: src/compose/ComposeMenu.js (hunk 1 above)
Comment (borisyankov) [reply src/compose/ComposeMenu.js]: Yeah, keeping it in the same directory but outside the `ComposeMenu` makes sense. We don't use that approach often right now, but it is perfectly valid and we might want to use it more frequently. 👍

File: src/compose/ComposeMenu.js (hunk 2 above)
Comment (jackrzhang) [reply src/compose/ComposeMenu.js]: The function doesn't depend on anything particular to iOS to run, so such a check would be unnecessary. In the case that a user on Android attempts to upload a HEIC file (though, I'm not sure if that's even possible), the logic will be used.

File: src/compose/ComposeMenu.js (hunk 1 above)
Comment (jackrzhang) [reply src/compose/ComposeMenu.js]: I could have been more specific; I'm ok with keeping the function in the `ComposeMenu` file.

File: src/compose/ComposeMenu.js (hunk 2 above)
Comment (jackrzhang) [reply src/compose/ComposeMenu.js]: According to Wikipedia, [HEIF is supported by Android Pie](https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format#Support).

**Comment by gnprice** [comment]
Merged -- thanks @jackrzhang !

I added a change to give the helper a perhaps more meaningful name, and revise the jsdoc accordingly.
