### PR TITLE
Fix: Add indicator for when new message arrives

### LINKED ISSUE #349: Indicator for new messages
If the user had scrolled up and new message arrives, since the view does not scroll, display a bar telling that there are 'new unread messages'.

### PR DESCRIPTION
**Pull request by nashvail**
Fixes #349 

@borisyankov the onScroll surprisingly wasn't required in the implementation. `countUnread` handles the logic of when to show the indicator very well. I have added `position` prop to the `UnreadNotice` component which positions the notice on top or bottom of message list depending on what is supplies.

### CODE REVIEW

File: src/chat/UnreadNotice.js [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+    flex: 0.05,
+    width: 14,
+    height: 14,
+    margin: 8,
+    fontSize: 14,
+    color: 'white',
+    textAlign: 'center',
+  }
+  /*
+  crossIcon: {
```
Comment (borisyankov) [inline src/chat/UnreadNotice.js]: Remove comments ;)

File: src/chat/UnreadNotice.js [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+  duration: 400,
+  easing: Easing.bezier(0.17, 0.67, 0.11, 0.99)
+};
+
+export default class UnreadNotice extends React.Component {
+  constructor(props) {
+    super(props);
+
+    this.state = {
+      translateAnim: new Animated.Value(0)
```
Comment (borisyankov) [inline src/chat/UnreadNotice.js]: You can just use `translateAnimated` and then will not need to add `Anim` to the dict. It is still a reasonable name.

File: src/chat/UnreadNotice.js [hunk 3]
```diff
@@ -0,0 +1,114 @@
...
+  };
+
+  render() {
+    return (
+      <Animated.View style={this.dynamicContainerStyles()}>
+        <Icon style={[styles.icon, styles.downArrowIcon]} name="md-arrow-down" />
+        <Text style={styles.unreadText}>
+          New unread messages
+        </Text>
+        {/* Close Button */}
```
Comment (borisyankov) [inline src/chat/UnreadNotice.js]: Yeah, we'll likely want to add the 'Mark As Read' or something for the next PR. Remove this for now, please.

File: src/chat/UnreadNotice.js [hunk 4]
```diff
@@ -0,0 +1,114 @@
+import React from 'react';
```
Comment (borisyankov) [inline src/chat/UnreadNotice.js]: Sometimes in future, we might want to make all Notice components into one configurable component? Just a food for thought. It is fine as-is.

File: src/chat/Chat.js [hunk 5]
```diff
@@ -46,3 +51,9 @@ export default class Chat extends React.Component {
     );
   }
 }
+
+const mapStateToProps = (state) => ({
+  readIds: state.flags.read
```
Comment (borisyankov) [inline src/chat/Chat.js]: Move this to MainScreenContainer. We have all the state retrieval there and we pass it down.
We may think about moving them around a bit, but for now move there?

File: src/chat/UnreadNotice.js [hunk 6]
```diff
@@ -0,0 +1,114 @@
...
+          })
+        }
+      ]
+    };
+  };
+
+  render() {
+    return (
+      <Animated.View style={this.dynamicContainerStyles()}>
+        <Icon style={[styles.icon, styles.downArrowIcon]} name="md-arrow-down" />
```
Comment (borisyankov) [inline src/chat/UnreadNotice.js]: Have a look at `Icons.js` file. We use it to ensure we use only one icon type (since there are several Icon libs available), the file is self-explanatory.

**Comment by borisyankov** [comment]
Looks good 👍
